
version: '3.8'
services:
  db:
    image: mysql
    restart: always
    container_name: mysqldb-util-test
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local
